实体:
  疾病分类: 指保险公司会根据特定的疾病来进行赔付，这种特定疾病就是疾病分类里的某一种或多种
	等待期: 又名观察期，是指保险合同在生效的指定时期内，即使发生保险事故，受益人也不能获得保险赔偿，这段时期称为等待期
	意外免等待期: 在等待期内因为意外事故导致被保险人发生保险合同内的疾病时，免除等待期，依然进行正常的赔付
	费用报销范围: 指有医保报销、无医保报销、或者部分医保+自费药的费用报销方式
	公立医院等级: 医院按其功能、任务不同划分为一、二、三级等
	费用类别: 指保险公司报销被保险人因发生疾病或住院等不同类别的费用
	保障期类型: 一般指产品的保险期间，即合同生效后的保障时限
	最高投保年龄: 指保险产品最高可允许的投保人年龄，高于此年龄不可投保
	最低投保年龄: 指保险产品最低可允许的投保人年龄，低于此年龄不可投保
	事故场景: 在一些保险条款当中会出现特定场景的情况，只有在指定场景下发生意外保险才会进行赔付
	豁免原因: 指豁免对象（投保人或被保人）符合条款约定的豁免条件，从而履行条款规定豁免保费
	生效类型: 投保后有一个生效时间
	赔付比例: 指保险公司所承担的医疗费用的比例
	赔付限额: 责任保险的保险单中没有规定保险金额而只有赔偿限额，并以此赔偿限额作为保险人承担保险责任的最高限额，若索赔金额超出该赔偿限额，则超出部分由被保险人自负
	赔付次数: 指患上了某种疾病，保险公司可以赔付的次数
	续保免等待期: 指投保人续保以后，被保险人不需要重新经历等待期，也就是成功续保以后，一旦被保险人发生保险事故，被保险人都可以向保险公司申请理赔
	津贴计算方式: 津贴的给付方式，一般有一次性、按天、按次等方式
	单次事故免赔额: 免赔额它就是指保险公司不赔的部分，只有超过这个免赔限额，保险公司才给予赔付，单次事故免赔额就是指一次事故的免赔额
	赔付间隔期: 对于多次赔付的情况，约束两次赔付之间需要有一定的时间间隔
	累计天数上限: 对被保险人的住院、津贴给付等的最长天数限制
	医院类型: 大多数出现在医疗保险中，保险预防投保人与被保人骗保会规定医院的类型
	延长住院天数: 指保险公司不会因为治疗未结束而一直对被保险人承担医疗费用
	未成年人赔付规则: 指年龄未满18周岁的人，事故发生时赔付的比例是多少